spring:
  profiles: local
  datasource:
    sql-script-encoding: UTF-8
    initialization-mode: always
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:./data/testdb
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2_console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: false
    open-in-view: false
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

